<template>
<div class="terms1">
    <h2>TERMENI ȘI CONDIȚII DE ÎNCHIRIERE AUTO</h2>

<p>Art.1 Autoturismele se închiriează numai persoanelor ce posedă permis de conducere național sau internațional valabil, cu o vechime de cel puțin 3 ani și vârsta de peste 23 de ani, împliniți la data închirierii autoturismului.</p>
<p>Art.2 Actele necesare pentru închiriere sunt:<br>În original: permisul de conducere, pasaport, buletin sau carte de indentitate;</p>
<p>Art.3 Plata tarifului se va face în LEI, la cursul BNR din ziua plății.</p>
<p>Art. 4.1 La închiriere, clientul trebuie să depună o garanție corespunzătoare clasei de mașini închiriate, conform listei de prețuri&nbsp; afișate precum și costul închirierii propriu-zise.<br> Art. 4.2 Garanția servește pentru acoperirea pagubelor produse autovehiculului din vina clientului.<br> Art. 4.3 Garanția va fi restituită integral, în cazul în care autovehicolul închiriat este returnat la data și ora stabilită în contract, cu toate obiectele prevăzute în inventar, fără deteriorări interioare sau exterioare și alte daune, ce nu fac obiectul garanției, survenite pe perioada contractuală.</p>
<p>Art. 5&nbsp;Responsabilitatea clientului în cazul unui accident, a pierderii obiectelor de inventar sau deteriorarea bunurilor din interiorul masinii este în limita garanției depuse la închirierea autoturismului, numai dacă daunele sunt produse în limitele asigurării.</p>
<p>Art. 6 Tariful de închiriere include:<br> Art. 6.1: Limită de 300 km/zi,TVA, RCA, rovignetă,asigurare Casco;<br> Art. 6.2: Înlocuirea autoturismului defect, cu excepția cazurilor de defecțiune provocate din culpa clientului;<br> Art. 6.3: Revizii tehnice periodice la zi și întreținerea autoturismului;<br> Art. 6.4: Număr asistență: +40744802000.<br> Art. 6.5: Depășirea limitei de 300 km/zi se taxează suplimentar cu 0,1 EURO/km.</p>
<p>Art. 7 Tariful de închiriere nu include:<br> Art. 7.1: Combustibilul, taxele de trecere, garaj, transbordare pe timpul închirierii;<br> Art. 7.2: Asigurarea pentru persoanele și bagajele aflate în autoturism.<br> Art. 7.3: Amenzi datorate încălcării legislației de către client.</p>
<p>Art. 8 Alte tarife practicate, în urmatoarele situatii:<br> Art. 8.1: Taxata scaun de copil: 3 EUR, taxă lanțuri de zăpadă: 3 EURO, taxă GPS: 3 EURO/zi<br> Art. 8.2: Punerea la dispoziție a unui șofer pentru o perioadă mai mică sau egală cu 8h/zi, este taxată cu 30 EUR/zi;<br>Art. 8.3: Predarea autoturismului într-o altă locatie decât cea de unde s-a închiriat este taxata cu&nbsp;0.5 EUR/km.<br> Art. 8.4: Pentru realimentare cu carburant la restituirea autovehiculului se taxează 2 EURO/litru;<br> Art. 8.5: Depășirea timpului la restituirea mașinii cu mai mult de 2 ore fara anuntarea Companiei in prealabil se tarifează ca zi întreagă conform contractului;<br> Art. 8.6: Pentru constatarea lipsei sau deteriorării obiectelor de inventar menționate în contract, firma îsi rezervă dreptul de a reține, parțial sau total, din valoarea garanției depusă la închiriere;<br>Art. 8.7: Tarifele sunt aplicabile pentru închiriere pe teritoriul României, pentru închiriere în afara granițelor țării, tariful se majorează cu 10 EUR/zi și sunt necesare minim 3 zile de închiriere.</p>
<p>Art. 9 Clientul are următoarele obligații<br> 9.1: Să achite la încheierea contractului de închiriere a autoturismului contravaloarea perioadei de închiriere și a garanției aferente;<br> 9.2: Să mențină autoturismul într-o stare tehnică corespunzătoare cu cea pe care acesta o avea la data încheierii contractului de închiriere;<br> 9.3: Să cunoască și să respecte legile de circulație aplicabile;<br> 9.4: Să folosească autoturismul închiriat numai pe drumurile publice;<br> 9.5: Să asigure autoturismul închiriat în mod adecvat, împotriva furtului, vandalizarii sau a distrugerii;<br> 9.6: Să nu transporte pasageri contra unor sume de bani sau alte recompense materiale;<br> 9.7: Să nu folosească autoturismul închiriat în cadrul curselor automobilistice legale, ilegale sau antrenamente pentru acestea;<br> 9.8: Să nu remorcheze alte vehicule;<br> 9.9: Să nu avarieze partea inferioară a autoturismului închiriat prin acțiune sau neglijență;<br> 9.10: Să solicite împuternicire scrisa pentru iesirea din tara cu autoturismul închiriat cu cel putin 48 de ore înainte de data programata pentru plecare;<br> 9.11: Să nu părăsească cu autoturismul închiriat teritoriul României fără împuternicire scrisă de la SC Auto Data Rental SRL; în cazul în care clientul va părăsi teritoriul României, aceasta se va face ilegal, întreaga răspundere revine clientului inclusiv pentru daunele produse prin accident, furt sau cheltuielile de returnare ale autoturismului;<br> 9.12: Să respecte traseul declarat în împuternicire;<br> 9.13: Să nu încredințeze sau subînchirieze autoturismul terțelor persoane;<br> 9.14: Să sisteze calatoria si sa anunte reprezentantii SC Auto Data Rental SRL, la numarul NON STOP +40744802000, în cazul în care constata aspecte sau semne de funcționare defectuoasă a autoturismului și care pot periclită starea tehnică a autoturismului sau condițiile de securitate în circulația rutieră;<br> 9.15: Să nu angajeze reparații sau alte lucrări la autoturismul închiriat fără aprobarea scrisă a reprezentanților SC Auto Data Rental SRL; sumele plătite de client pentru lucrări de întreținere sau revizii tehnice scadențe pe parcurs ori pentru unele reparații ce nu îi sunt imputabile, se compensează de către SC Auto Data Rental SRL pe baza documentelor ce atestă efectuarea acestor lucrări: factura fiscală și chitanța cu datele firmei;<br> 9.16: Să nu provoace pagube zonei exterioare, interioare sau la roți, cu intenție sau din neglijență, printr-o folosire necorespunzatoare a acestora;<br> 9.17: Să restituie autoturismul închiriat la data, ora și locația prevăzută în contract; prelungirea termenului de închiriere se poate face numai cu aprobarea scrisă a SC Auto Data Rental SRL; folosirea autoturismului peste termenul de închiriere, fără o aprobare prealabilă scrisă în acest sens, constituie un act de însușire ilegală a bunului și se sancționează conform legislației în vigoare.</p>
<p>Art.10&nbsp;Nerespectarea obligațiilor menționate mai sus duce la încetarea efectului asigurărilor iar răspunderea pentru daunele provocate revine în totalitate clientului, inclusiv venitul nerealizat pe perioada imobilizării autoturismului închiriat.</p>
<p>Art.11&nbsp;În cazul unui accident, clientul este obligat:<br> 11.1: Să ia toate măsurile pentru limitarea pagubelor produse;<br> 11.2: Să anunțe cel mai apropiat organ de poliție, de pe raza localității în care s-a produs accidentul, în vederea constatării accidentului și întocmirii formelor legale; să anunțe reprezentanții SC Auto Data Rental SRL, la numărul de asistență +40744802000, în maxim 2 ore de la producerea accidentului;<br> 11.3: Să respecte regulile rutiere privind părăsirea locului accidentului;<br> 11.4: Să procure o copie după buletinul și permisul de conducere a persoanei implicate în eveniment precum, o declarație scrisă a acesteia și o copie dupa RCA;<br> 11.5: Să procure autorizația de reparație de la organele competente.</p>
<p>Art.12:&nbsp;Prezentul contract are valoare de titlu executoriu, clientul acceptând în mod expres și irevocabil predarea bunului către companie fără somație, notificare prealabilă sau proces.<br><br> Art.13&nbsp;Orice litigiu izvorat din acest contract sau în legatură cu acesta, inclusiv validitatea, interpretarea, executarea sau desființarea lui se va soluționa în prealabil pe cale amiabilă iar, în caz contrar, de către instanțele judecătorești de pe raza municipiului Cluj-Napoca.</p>
<p>Art.14&nbsp;Litigiul în cauză va fi soluționat întotdeauna conform legii române.</p>
<p>Art.15&nbsp;SC Auto Data Rental SRL îsi păstrează dreptul de a recupera de la utilizator sau client contravaloare pagubelor produse peste limita garanției, în situațiile în care clientul sau utilizatorul încalcă obligațiile prezentului contract, în conformitate cu legile în vigoare.</p>
<p>Art.16&nbsp;Prin semnarea prezentului contract, clientul recunoaște că a citit, a înteles și se obligă să respecte prezentele condiții de închiriere ca parte integrantă a contractului.</p>
<p>Art.17&nbsp;Clientul are obligația de a preda mașina curată, astfel încât să poată fi verificată. Garanția se deblochează numai după verificare.</p>
</div>
</template>

<style lang="scss" scoped>
@import "../scss/variables.scss";
.terms1{
background: url("../assets/img-terms.jpg");
}
</style>